<table class="table">
    <thead>
	<tr>
            <th>
		Datetime
            </th>
            <th>
		Code
            </th>
            <th>
		Action
            </th>
            <th>
		Amount
            </th>
	</tr>
    </thead>
<tbody>
<tr>
            <td>
		{Datetime}
            </td>
            <td>
		{Code}
            </td>
            <td>
                {Action}
            </td>
            <td>
                {Amount}
            </td>
	</tr>
    </tbody>
</table>